name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote server to known hosts
        run: ssh-keyscan ${{ secrets.REMOTE_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Pull code on GitHub server
        run: git pull origin main

      - name: Rsync code to remote server
        run: |
          rsync -avz --delete --exclude='.git' --exclude='node_modules' . ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_SERVER_IP }}:/home/ubuntu/test

      - name: Clean up
        run: ssh-agent -k

